/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    jacoco
	java
    `java-library`
    id("application")
    id("org.openjfx.javafxplugin") version "0.1.0"
    
}

javafx {
    version = "21"
    modules("javafx.controls", "javafx.fxml")
}
jacoco {
    toolVersion = "0.8.10"  // Ensure you are using a compatible version
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.0")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.8.0")
        
       testImplementation ("org.mockito:mockito-core:3.12.4")
   
        testRuntimeOnly ("org.junit.jupiter:junit-jupiter-engine:5.8.0")
        
    
    implementation("org.antlr:antlr4:4.9.2")
    implementation("org.antlr:antlr4-runtime:4.9.2")
    implementation("com.formdev:flatlaf:1.1.1")
    implementation("org.postgresql:postgresql:42.2.10")
    
}
sourceSets {
    main {
        java {
            setSrcDirs(listOf("src"))
        }
        resources {
            setSrcDirs(listOf("src"))
            files("**/*.css")
        }
    }

    test {
        java {
            setSrcDirs(listOf("testManual","test","testLLM"))
        }
    }
}

tasks.test {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
    testLogging {
        events("passed", "skipped", "failed")
    }
}
tasks.jacocoTestReport {
    dependsOn(tasks.test)
    classDirectories.setFrom(
        fileTree(mapOf(
            "dir" to "${buildDir}/classes/java/main",
            "includes" to listOf("**/*.class"),
            "excludes" to listOf(
                "guicontrol/**",
                "guilayout/**",
            )
        ))
    )
    sourceDirectories.setFrom(files("src/backend/"))
    executionData.setFrom(files("${buildDir}/jacoco/test.exec"))

    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}

application {
  mainClass.set("guilayout.ApplicationStart")  
}

group = "PawfectPairs"
version = "0.0.1-SNAPSHOT"
description = "PawfectPairs"
java.sourceCompatibility = JavaVersion.VERSION_1_8