/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
	java
    `java-library`
    id("application")
    id("org.openjfx.javafxplugin") version "0.1.0"
    
}

javafx {
    version = "21"
    modules("javafx.controls", "javafx.fxml")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.0")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.7.0")
    implementation("org.antlr:antlr4:4.9.2")
    implementation("org.antlr:antlr4-runtime:4.9.2")
    implementation("com.formdev:flatlaf:1.1.1")
    implementation("org.postgresql:postgresql:42.2.10")
}
sourceSets {
    main {
        java {
            setSrcDirs(listOf("src"))
        }
        resources {
            setSrcDirs(listOf("src"))
            files("**/*.css")
        }
    }

    test {
        java {
            setSrcDirs(listOf("test"))
        }
    }
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}

application {
  mainClass.set("guilayout.ApplicationStart")  
}

group = "PawfectPairs"
version = "0.0.1-SNAPSHOT"
description = "PawfectPairs"
java.sourceCompatibility = JavaVersion.VERSION_1_8