package gui.layouts;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import gui.layouts.DogProfile;

/*

Application start. Temp main menu generated by Chat GPT


*/

public class ApplicationStart extends Application {

    @Override
    public void start(Stage stage) {
        Label l = new Label("Hello world!!!!!");
        Scene scene = new Scene(new StackPane(l), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        // launch(); // launch THIS class

//        Application.launch(DogProfile.class, args); // launch a different class. 
    	DogProfile.main(args);
    }

}