package gui.layouts;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;


/*

Temporary profile page generated by ChatGPT

*/

public class DogProfile extends Application {

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Pet Profile");

        // Create a GridPane layout
        GridPane gridPane = new GridPane();
        gridPane.setVgap(10);
        gridPane.setHgap(10);

        // Pet photo
        Image petImage = new Image("file:pet_photo.jpg"); // Replace with your image file path
        ImageView imageView = new ImageView(petImage);
        imageView.setFitWidth(150);
        imageView.setFitHeight(150);
        gridPane.add(imageView, 0, 0, 2, 1); // span 2 columns

        // Pet information
        Label nameLabel = new Label("Name: Fido");
        Label ageLabel = new Label("Age: 3 years");
        Label breedLabel = new Label("Breed: Labrador");

        gridPane.add(nameLabel, 0, 1);
        gridPane.add(ageLabel, 0, 2);
        gridPane.add(breedLabel, 0, 3);

        // Pet stats
        Label energyLabel = new Label("Energy Level: High");
        Label sizeLabel = new Label("Size: Medium");

        gridPane.add(energyLabel, 1, 1);
        gridPane.add(sizeLabel, 1, 2);

        // Set the layout as the scene root
        Scene scene = new Scene(gridPane, 400, 300);

        // Set the scene for the stage
        primaryStage.setScene(scene);

        // Show the stage
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}